version: '3.8'

services:
  postgres_master:
    container_name: postgres_master
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-script/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./data-slave:/var/lib/postgresql/data-slave
      - ./init-script:/etc/postgresql/init-script
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"

  postgres_slave:
    container_name: postgres_slave
    image: postgres:latest
    restart: always
    volumes:
      - ./data-slave:/var/lib/postgresql/data
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
