version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_data/:/var/lib/db_data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
